apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mission-control
resources:
- ../../base
# Use labels with includeSelectors: false to avoid breaking external services
labels:
- pairs:
    environment: prod
  includeSelectors: false
images:
- name: docker.toastedbytes.com/pete-bot
  digest: sha256:30713b98c8e44d16dd5be3d6495c82b4052388f9e732d857bb8d1e513cb977fb
