apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pete-bot
resources:
- ../../base
# Use labels with includeSelectors: false to avoid breaking external services
labels:
- pairs:
    environment: prod
  includeSelectors: false
images:
- name: docker.toastedbytes.com/pete-bot
  digest: sha256:6b90b3f44d91193cdab1450dd0d973b5da77687ecb4b55ad9fa0f4f7718ec434
